import type { Metadata } from "next";
import "./globals.css";
import Providers from "../redux/providers";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${openSans.className} w-screen h-screen`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
